version: '3.2'

services:
    wordpress:
        image: wordpress:latest
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_NAME: wordpressdb
            WORDPRESS_DB_USER: mouras
            WORDPRESS_DB_PASSWORD: toor
        ports:
            - 8080:80
    db:
        image: mariadb
        environment:
            MYSQL_ROOT_PASSWORD: toor
            MYSQL_DATABASE: wordpressdb
            MYSQL_USER: mouras
            MYSQL_PASSWORD: toor
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8081:80
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORT: toor

